### ISSUE TITLE
ANIMATION BUG: Inverted rudder animation axis 

### ISSUE THREAD

**Issue by Cubeboyy** [PucaraPastrana/PucaraDCS#2]
**Bug:** Inverted rudder animation axis

**Description:** The animation on the rudder seems to be inverted. When left rudder is applied, the rudder moves to the right and viceversa. The animation argument seems to be inverted only on the rudder as it is correct with the nose wheel movement.

**Expected behavior:** If left pedal is applied, the rudder should move to the left and viceversa.

**Version info:** 
DCS Latest OB 2.7.3.8494
Pucará Public Release 0.0.3b

**Comment by PucaraPastrana** [comment]
Thanks is corrected for the next update. Thanks.
