### ISSUE TITLE
lifted gunsight texture from A-4E-C

### ISSUE THREAD

**Issue by callmepartario** [PucaraPastrana/PucaraDCS#3]

**Comment by PucaraPastrana** [comment]
A simple texture, and you question between this little world. Please. When I have time and desire, I make one.

**Comment by callmepartario** [comment]
ok

**Comment by Cubeboyy** [comment]
He is right. 
It is his work, and one that took him a while to do. That texture work belongs to the A-4E Community project. 

If it is that easy, then why don't you make one that is actually accurate to the one that was equipped on the aircraft?

**Comment by kevotosmart** [comment]
Grow up, go read a book. Over here spreading GitHub drama links on the forums. What are you 12?

**Comment by kevotosmart** [comment]
> can really tell how proud you are by how you deleted the contents of the initial report.
> 
> if it's such a small matter. fix it, and get your shit right, you fuckin' thief.

Grow up little boy, over here posting links on the forums to stir up some drama.

**Comment by 08jne01** [comment]
> A simple texture, and you question between this little world. Please. When I have time and desire, I make one.

The A-4E project is generous enough to let you use all the lua code you want, yet you want to take advantage by just lifting our textures?

Plus you are making money using patreon even though you have stolen our texture.

**Comment by PucaraPastrana** [comment]
> > Una textura simple, y te cuestionas entre este pequeño mundo. Por favor. Cuando tengo tiempo y ganas, hago uno.
> 
> El proyecto A-4E es lo suficientemente generoso como para permitirle usar todo el código lua que desee, pero ¿desea aprovechar simplemente levantando nuestras texturas?
> 
> Además, está ganando dinero con patreon a pesar de que ha robado nuestra textura.

15 dolar? 
Earning money?

**Comment by PucaraPastrana** [comment]
> He is right.
> It is his work, and one that took him a while to do. That texture work belongs to the A-4E Community project.
> 
> If it is that easy, then why don't you make one that is actually accurate to the one that was equipped on the aircraft?


next update

**Comment by kevotosmart** [comment]
> ok

I don’t even have this mod, I just love seeing all you dcs children and your high school drama or bitching . Just about as toxic as the arma community lol

**Comment by 08jne01** [comment]
> > ok
> 
> I don’t even have this mod, I just love seeing all you dcs children and your high school drama or bitching . Just about as toxic as the arma community lol

You know what when you actually make something it's not nice for people to lift your stuff and use it in their project. Then when politely confronted about it, they remove the post and close the issue. If you hate drama so much why "add" to it by commenting.

**Comment by kevotosmart** [comment]
> > > ok
> > 
> > 
> > I don’t even have this mod, I just love seeing all you dcs children and your high school drama or bitching . Just about as toxic as the arma community lol
> 
> You know what when you actually make something it's not nice for people to lift your stuff and use it in their project. Then when politely confronted about it, they remove the post and close the issue. If you hate drama so much why "add" to it by commenting.

It’s hilarious to see you little kids fuzzing and crying, about as toxic as arma. You mad or something child?

**Comment by PucaraPastrana** [comment]
It is already cleared up, update will be up shortly with the original Pucara sight.  Let's enjoy the airplanes, the game that nobody becomes a millionaire with this.  The purpose is to give everyone another plane to fly and enjoy this excellent game that ED offers us.

**Comment by 08jne01** [comment]
> It is already cleared up, update will be up shortly with the original Pucara sight. Let's enjoy the airplanes, the game that nobody becomes a millionaire with this. The purpose is to give everyone another plane to fly and enjoy this excellent game that ED offers us.

As I said to you on discord, you have until the end of the day to remove the copyrighted material from your github or we will file a DMCA takedown notice to github on your repo. This could have been resolved politely, but you chose to make it difficult.
